context:
  version: "0.3.0"
  python_min: "3.10"

package:
  name: napari-metadata
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/napari-metadata/napari_metadata-${{ version }}.tar.gz
  sha256: 89ef0d7543dd0a8f74fc1bf5227907d9b5d821f82f380f69078d5a572677539b

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python >=${{ python_min }}
    - setuptools >=77.0.3
    - setuptools_scm
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - qtpy
    - pint
    - typing_extensions
    - superqt

tests:
  - python:
      imports:
        - napari_metadata.units
      pip_check: true

about:
  summary: View and edit napari layer metadata
  description: |
    napari-metadata is a plugin that exposes napari layer metadata as a GUI for
    viewing and editing.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/napari/napari-metadata
  homepage: https://github.com/napari/napari-metadata
  documentation: https://github.com/napari/napari-metadata#README.md

extra:
  recipe-maintainers:
    - conda-forge/napari
    - carlosmariorr
    - TimMonko
